# Generated by Django 2.1.7 on 2019-03-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
