# Generated by Django 2.2 on 2019-04-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='inProgress',
            field=models.BooleanField(default=0),
        ),
    ]
