# Generated by Django 2.2 on 2019-04-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
