# Generated by Django 2.2.3 on 2019-08-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190430_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
